spec          := <'%%'> (docker-spec / env-spec) [<'||'> default-value] <'%%'>

env-spec      := [<'env'> [options] link-type] target

docker-spec   := [<'docker'>] [options] link-type target

options       := <'['> option ( <','> option )*  <']'>

option        := addr-opt / port-opt / sep-opt
addr-opt      := <'addr'>
port-opt      := <'port'>
sep-opt       := <'sep='> #"[^\],]*"

target        := #"[^>:%|]+" [':' port]

port          := #"[0-9]+"

link-type     := multiple-link | single-link
multiple-link := <'>>'>
single-link   := <'>'>

default-value := #"[^%]*"


